export { OwnerDashboardPage } from './dashboard'
export { OwnerReservationsPage } from './reservations'
export { OwnerStorePage } from './store'
export { OwnerTablesPage } from './tables'
export { OwnerWaitingsPage } from './waitings'
export { OwnerHoursPage } from './hours'
export { OwnerPolicyPage } from './policy'
